
version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-segredo-edson-compose}
    command: ["node", "server.js"]
  graphql:
    build: .
    ports:
      - "4000:4000"
    environment:
      - GRAPHQL_PORT=4000
      - JWT_SECRET=${JWT_SECRET:-segredo-edson-compose}
    command: ["node", "graphql/server.js"]
